<a href="https://colab.research.google.com/github/codewithsamiksha/Model_Training/blob/main/Task22(Logistick_regeration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Q1
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving heart - heart.csv to heart - heart.csv

In [2]:
filepath = 'heart - heart.csv'
df= pd.read_csv(filepath)
print(df)

     Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal
1     49   F           NAP        160          180          0     Normal
2     37   M           ATA        130          283          0         ST
3     48   F           ASY        138          214          0     Normal
4     54   M           NAP        150          195          0     Normal
..   ...  ..           ...        ...          ...        ...        ...
913   45   M            TA        110          264          0     Normal
914   68   M           ASY        144          193          1     Normal
915   57   M           ASY        130          131          0     Normal
916   57   F           ATA        130          236          0        LVH
917   38   M           NAP        138          175          0     Normal

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease
0      172              N      0.0       Up             0
1      156              N      1.0     Flat             1
2       98              N      0.0       Up             0
3      108              Y      1.5     Flat             1
4      122              N      0.0       Up             0
..     ...            ...      ...      ...           ...
913    132              N      1.2     Flat             1
914    141              N      3.4     Flat             1
915    115              Y      1.2     Flat             1
916    174              N      0.0     Flat             1
917    173              N      0.0       Up             0

[918 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [15]:
#Q1
data scaling
X = df.drop(columns=["HeartDisease"], axis = 1)
Y = df['HeartDisease']
print("Input Features:")
print(X)
print("Output Features:")
print(Y)

#one hot encoding
cat_cols = X.select_dtypes(include="object").columns
print(cat_cols)

X = pd.get_dummies(X, columns=cat_cols)
X.head()

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,False,True,False,True,False,False,False,True,False,True,False,False,False,True
1,49,160,180,0,156,1.0,True,False,False,False,True,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,False,True,False,True,False,False,False,False,True,True,False,False,False,True
3,48,138,214,0,108,1.5,True,False,True,False,False,False,False,True,False,False,True,False,True,False
4,54,150,195,0,122,0.0,False,True,False,False,True,False,False,True,False,True,False,False,False,True

In [5]:
cat_cols = X.select_dtypes(include="object").columns
print(cat_cols)

X = pd.get_dummies(X, columns=cat_cols)
X.head()

Index([], dtype='object')

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,False,True,False,True,False,False,False,True,False,True,False,False,False,True
1,49,160,180,0,156,1.0,True,False,False,False,True,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,False,True,False,True,False,False,False,False,True,True,False,False,False,True
3,48,138,214,0,108,1.5,True,False,True,False,False,False,False,True,False,False,True,False,True,False
4,54,150,195,0,122,0.0,False,True,False,False,True,False,False,True,False,True,False,False,False,True

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=42
)
print("X_train :", X_train.shape)
print("X_test :", X_test.shape)
print("Y_train :", Y_train.shape)
print("Y_test :", Y_test.shape)

X_train : (734, 20)
X_test : (184, 20)
Y_train : (734,)
Y_test : (184,)

In [18]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, Y_train)
# print("Model Train sucessfully")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [8]:
# Q4
y_pred = model.predict(X_test)
print("Actual Values")
print(Y_test.head(10))
print()
print("Predicted Values")
print(y_pred[:10])

Actual Values
668    0
30     1
377    1
535    1
807    0
793    1
363    1
583    0
165    1
483    1
Name: HeartDisease, dtype: int64

Predicted Values
[0 0 1 1 0 1 1 0 1 1]

In [9]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, y_pred)

print(cm)

TN, FP, FN, TP = cm.ravel()

print("True Negative : ", TN)
print("False Positive : ", FP)
print("False Negative : ", FN)
print("True Positive : ", TP)

[[67 10]
 [17 90]]
True Negative :  67
False Positive :  10
False Negative :  17
True Positive :  90

In [19]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

print("Accuracy : ", accuracy_score(Y_test, y_pred))
print("Precision : ", precision_score(Y_test, y_pred))
print("Recall : ", recall_score(Y_test, y_pred))
print("F1 Score : ",f1_score(Y_test, y_pred))
print()

print(classification_report(Y_test, y_pred))

Accuracy :  0.8532608695652174
Precision :  0.9
Recall :  0.8411214953271028
F1 Score :  0.8695652173913043

              precision    recall  f1-score   support

           0       0.80      0.87      0.83        77
           1       0.90      0.84      0.87       107

    accuracy                           0.85       184
   macro avg       0.85      0.86      0.85       184
weighted avg       0.86      0.85      0.85       184

##KNN Regression Algorithum

In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

model_KNN = KNeighborsClassifier(n_neighbors = 5)
model_KNN.fit(X_train, Y_train)

print("Accuracy Score Of K-Nearest Neighbors(5):")
pred_KNN = model.predict(X_test)
accuracy_score(pred_KNN, Y_test)

Accuracy Score Of K-Nearest Neighbors(5):

0.8532608695652174

In [35]:
#Training the model
model_KNN = KNeighborsClassifier(n_neighbors=3)
model_KNN.fit(X_train, Y_train)

#finding accuracy score
print("Accuracy Score of K-Nearest Neighbors(3):")
pred_KNN = model.predict(X_test)
accuracy_score(pred_KNN, Y_test)

Accuracy Score of K-Nearest Neighbors(3):

0.8532608695652174

In [36]:
#Traingn Model
model_KNN = KNeighborsClassifier(n_neighbors = 7)
model_KNN.fit(X_train, Y_train)

#Finding accuracy score
print("Accuracy Score of K-Nearest Neighbors(7):")
pred_KNN = model.predict(X_test)
accuracy_score(pred_KNN, Y_test)

Accuracy Score of K-Nearest Neighbors(7):

0.8532608695652174

##Naive Bayes

In [25]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()
model_NB.fit(X_train, Y_train)

GaussianNB()

In [40]:
from sklearn.metrics import(
    classification_report,
    confusion_matrix
)

# Predict using the Naive Bayes model
pred_NB = model_NB.predict(X_test)

cm = confusion_matrix(
    Y_test,
    pred_NB
  )
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[70  7]
 [18 89]]

In [42]:
#classification report
report = classification_report(
    Y_test,
    pred_NB
)
print("Classification Report:")
print(report)

#accuracy score
print("Accuracy Score of Naive Bayes:")
accuracy_score(pred_NB, Y_test)

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.91      0.85        77
           1       0.93      0.83      0.88       107

    accuracy                           0.86       184
   macro avg       0.86      0.87      0.86       184
weighted avg       0.87      0.86      0.86       184

Accuracy Score of Naive Bayes:

0.8641304347826086

In [45]:
comparison = pd.DataFrame(
    results,
    columns=[
        "Algorithum",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)
comparison

            Algorithum  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.853261   0.900000  0.841121  0.869565
1  K-Nearest Neighbors  0.663043   0.731959  0.663551  0.696078
2          Naive Bayes  0.864130   0.927083  0.831776  0.876847

In [11]:
# import joblib
# joblib.dump(model, "heart_model.pkl")
# joblib.dump(X.columns.tolist(), "columns.pkl")

In [12]:
# from google.colab import files
# files.download("heart_model.pkl")
# files.download("columns.pkl")
# # files.download("scaler.pkl")